// Deterministic PRNG — splitmix64. Direct port of Simulation/SeededRNG.swift.
//
// CRITICAL: all 64-bit arithmetic uses BigInt. JS `number` loses precision above
// 2^53, and a single silent overflow desyncs the sequence from Swift. Validated
// bit-for-bit against test/vectors/*.json (generated by the Python oracle).
const MASK64 = (1n << 64n) - 1n;
const GAMMA = 0x9e3779b97f4a7c15n;
const MIX1 = 0xbf58476d1ce4e5b9n;
const MIX2 = 0x94d049bb133111ebn;

// 1.0 / 2^53 is exactly representable (power of two), so nextDouble matches the
// Swift/Python `* (1.0 / Double(1 << 53))` formula bit-for-bit.
const INV_2_53 = 1.0 / 2 ** 53;

export class SeededRNG {
  private state: bigint;

  constructor(seed: bigint | number) {
    const s = BigInt(seed) & MASK64;
    // Avoid a zero state, which would produce a degenerate sequence.
    this.state = s === 0n ? GAMMA : s;
  }

  // Mirrors SeededRNG.next() — the splitmix64 step.
  next(): bigint {
    this.state = (this.state + GAMMA) & MASK64;
    let z = this.state;
    z = ((z ^ (z >> 30n)) * MIX1) & MASK64;
    z = ((z ^ (z >> 27n)) * MIX2) & MASK64;
    return (z ^ (z >> 31n)) & MASK64;
  }

  // Uniform Double in [0, 1).
  nextDouble(): number {
    return Number(this.next() >> 11n) * INV_2_53;
  }

  // Uniform Double in a closed range.
  nextDoubleIn(lo: number, hi: number): number {
    return lo + this.nextDouble() * (hi - lo);
  }

  // Uniform Int in a closed range — plain modulo, matching Swift's *custom*
  // `SeededRNG.nextInt(in:)`: `lo + Int(next() % span)`. Always consumes exactly one
  // next() draw (even when span == 1). WheelFactory uses this for false-gate counts.
  // NOTE: this is NOT the same as stdlib Int.random / shuffle — see nextUpperBound.
  nextInt(lo: number, hi: number): number {
    const span = BigInt(hi - lo + 1);
    return lo + Number(this.next() % span);
  }

  // Swift stdlib `RandomNumberGenerator.next(upperBound:)` — Lemire's "nearly
  // divisionless" method (multiply-high with a rejection tail). Returns a value in
  // [0, bound). This is what `Int.random(in:using:)` and `Array.shuffle(using:)` use
  // internally — DISTINCT from nextInt above (which is plain modulo). Getting this
  // wrong reorders base heights for any seed whose shuffle isn't the identity.
  nextUpperBound(bound: bigint): bigint {
    let random = this.next();
    let m = random * bound;
    let low = m & MASK64;
    if (low < bound) {
      const t = ((1n << 64n) - bound) % bound; // == (0 &- bound) % bound in Swift
      while (low < t) {
        random = this.next();
        m = random * bound;
        low = m & MASK64;
      }
    }
    return m >> 64n; // high 64 bits
  }

  // Swift `Int.random(in: lo ..< hiExclusive, using:)` — half-open.
  randomInt(lo: number, hiExclusive: number): number {
    return lo + Number(this.nextUpperBound(BigInt(hiExclusive - lo)));
  }

  // Swift `Array.shuffle(using:)` — Fisher-Yates, forward, using next(upperBound:).
  // Mutates in place. The upperBound sequence is [count, count-1, ..., 2].
  shuffle<T>(arr: T[]): void {
    let amount = arr.length;
    if (amount <= 1) return;
    let currentIndex = 0;
    while (amount > 1) {
      const random = Number(this.nextUpperBound(BigInt(amount)));
      amount -= 1;
      const j = currentIndex + random;
      const tmp = arr[currentIndex];
      arr[currentIndex] = arr[j];
      arr[j] = tmp;
      currentIndex += 1;
    }
  }
}
