// Deterministic PRNG — splitmix64. Direct port of Simulation/SeededRNG.swift.
//
// CRITICAL: all 64-bit arithmetic uses BigInt. JS `number` loses precision above
// 2^53, and a single silent overflow desyncs the entire sequence from Swift/Python.
// Validated bit-for-bit against test/vectors/rng.json (generated by the Python oracle).
const MASK64 = (1n << 64n) - 1n;
const GAMMA = 0x9e3779b97f4a7c15n;
const MIX1 = 0xbf58476d1ce4e5b9n;
const MIX2 = 0x94d049bb133111ebn;

// 1.0 / 2^53 is exactly representable (power of two), so nextDouble matches the
// Swift/Python `* (1.0 / Double(1 << 53))` formula bit-for-bit.
const INV_2_53 = 1.0 / 2 ** 53;

export class SeededRNG {
  private state: bigint;

  constructor(seed: bigint | number) {
    const s = BigInt(seed) & MASK64;
    // Avoid a zero state, which would produce a degenerate sequence.
    this.state = s === 0n ? GAMMA : s;
  }

  // Mirrors SeededRNG.next() — the splitmix64 step.
  next(): bigint {
    this.state = (this.state + GAMMA) & MASK64;
    let z = this.state;
    z = ((z ^ (z >> 30n)) * MIX1) & MASK64;
    z = ((z ^ (z >> 27n)) * MIX2) & MASK64;
    return (z ^ (z >> 31n)) & MASK64;
  }

  // Uniform Double in [0, 1).
  nextDouble(): number {
    return Number(this.next() >> 11n) * INV_2_53;
  }

  // Uniform Double in a closed range.
  nextDoubleIn(lo: number, hi: number): number {
    return lo + this.nextDouble() * (hi - lo);
  }

  // Uniform Int in a closed range — plain modulo (matches Swift nextInt(in:)).
  // Modulo bias is negligible for small ranges. Used by count draws.
  nextInt(lo: number, hi: number): number {
    const span = BigInt(hi - lo + 1);
    return lo + Number(this.next() % span);
  }

  // Rejection-sampling integer draw — matches what Swift's Int.random(in:using:)
  // and Array.shuffle(using:) consume internally (the `swift_int` reconstruction in
  // diagnostic_sim.py). DISTINCT from nextInt: this rejects to remove modulo bias, so
  // it draws next() one-or-more times. WheelFactory (Phase 1) relies on this exact path
  // for base-height ordering — getting it wrong desyncs every downstream wheel value.
  swiftInt(lo: number, hi: number): number {
    const delta = hi - lo + 1;
    if (delta <= 1) return lo;
    const upperBound = BigInt(delta);
    const tmp = (MASK64 % upperBound) + 1n; // MASK64 == T.max == 2^64 - 1
    const rejectionRange = tmp === upperBound ? 0n : tmp;
    for (;;) {
      const r = this.next();
      if (r >= rejectionRange) return lo + Number(r % upperBound);
    }
  }
}
