#!/usr/bin/env python3
"""Generate RNG + AngleNormalizer parity fixtures for the TypeScript port.

This is the *oracle* for Phase 0: it reproduces, bit-for-bit, the algorithms in
the Swift app's `SeededRNG.swift` (splitmix64) and the rejection-sampling integer
draw that Swift's `Array.shuffle(using:)` / `Int.random(in:using:)` uses — the
`swift_int` reconstruction from `diagnostic_sim.py`. It also emits AngleNormalizer
expectations.

Run:  python3 tools/gen_rng_fixtures.py
Writes: test/vectors/rng.json  and  test/vectors/angle.json

The TypeScript SeededRNG/AngleNormalizer ports are asserted against these fixtures
in test/parity/*.test.ts. 64-bit values are emitted as decimal strings (they can
exceed JS Number.MAX_SAFE_INTEGER) and parsed back as BigInt on the TS side.
"""
import json, math, os

MASK64 = 0xFFFFFFFFFFFFFFFF
def u64(x): return x & MASK64

class SeededRNG:
    def __init__(self, seed):
        self.state = u64(0x9e3779b97f4a7c15) if seed == 0 else u64(seed)

    def next(self):
        self.state = u64(self.state + 0x9e3779b97f4a7c15)
        z = self.state
        z = u64((z ^ (z >> 30)) * 0xbf58476d1ce4e5b9)
        z = u64((z ^ (z >> 27)) * 0x94d049bb133111eb)
        return z ^ (z >> 31)

    def next_double(self):
        return (self.next() >> 11) * (1.0 / (1 << 53))

    def next_double_in(self, lo, hi):
        return lo + self.next_double() * (hi - lo)

    def next_int(self, lo, hi):
        span = hi - lo + 1
        return lo + (self.next() % span)

    def swift_int(self, lo, hi):
        """Swift stdlib Int.random(in:using:) — rejection sampling on next() % upperBound."""
        delta = hi - lo + 1
        if delta <= 1:
            return lo
        upper_bound = delta
        tmax = (1 << 64) - 1
        tmp = (tmax % upper_bound) + 1
        rejection_range = 0 if tmp == upper_bound else tmp
        while True:
            r = self.next()
            if r >= rejection_range:
                return lo + (r % upper_bound)


def next_sequence(seed, n):
    rng = SeededRNG(seed)
    return [str(rng.next()) for _ in range(n)]

def double_sequence(seed, n):
    rng = SeededRNG(seed)
    # repr() gives the shortest round-trippable decimal — matches IEEE-754 exactly
    return [repr(rng.next_double()) for _ in range(n)]

def double_in_sequence(seed, lo, hi, n):
    rng = SeededRNG(seed)
    return [repr(rng.next_double_in(lo, hi)) for _ in range(n)]

def next_int_sequence(seed, lo, hi, n):
    rng = SeededRNG(seed)
    return [rng.next_int(lo, hi) for _ in range(n)]

def swift_int_calls(seed, calls):
    """calls: list of [lo, hi]; returns list of results in order."""
    rng = SeededRNG(seed)
    return [rng.swift_int(c[0], c[1]) for c in calls]


rng_fixtures = {
    "_comment": "Generated by tools/gen_rng_fixtures.py — oracle for the TS SeededRNG port. 64-bit ints are decimal strings.",
    "next": {
        # seed 42 exercised 20 deep (mirrors SeededRNGTests deterministic loop)
        "42": next_sequence(42, 20),
        "1": next_sequence(1, 1),
        "2": next_sequence(2, 1),
        "0": next_sequence(0, 1),      # remapped away from zero; must be nonzero + deterministic
        "12345": next_sequence(12345, 10),
        "99": next_sequence(99, 4),
    },
    "nextDouble": {
        "99": double_sequence(99, 8),
        "7": double_sequence(7, 8),
    },
    "nextDoubleIn": {
        # seed 7, range -5..5 (mirrors SeededRNGTests closed-range test)
        "7:-5:5": {"seed": 7, "lo": -5.0, "hi": 5.0, "values": double_in_sequence(7, -5.0, 5.0, 8)},
    },
    "nextInt": {
        # seed 13, range 0..39 (mirrors SeededRNGTests nextInt bounds test)
        "13:0:39": {"seed": 13, "lo": 0, "hi": 39, "values": next_int_sequence(13, 0, 39, 20)},
    },
    "swiftInt": {
        # A backward Fisher-Yates draw pattern (swift_int(0, i) for i=9..1) + a flat range.
        "77:fisherYates10": {
            "seed": 77,
            "calls": [[0, i] for i in range(9, 0, -1)],
            "results": swift_int_calls(77, [[0, i] for i in range(9, 0, -1)]),
        },
        "12345:flat": {
            "seed": 12345,
            "calls": [[0, 39]] * 12,
            "results": swift_int_calls(12345, [[0, 39]] * 12),
        },
        "1:degenerate": {
            "seed": 1,
            "calls": [[5, 5], [3, 3]],   # delta <= 1 → returns lo without drawing
            "results": swift_int_calls(1, [[5, 5], [3, 3]]),
        },
    },
}


# ── AngleNormalizer ─────────────────────────────────────────────────────────
def circular_distance(a, b, r):
    diff = math.fmod(a - b, r)
    if diff < 0:
        diff += r
    return min(diff, r - diff)

def normalize_position(p, r):
    mod = math.fmod(p, r)
    if mod < 0:
        mod += r
    return mod

angle_cases = []
for (a, b, r) in [(10, 90, 100), (90, 10, 100), (0, 0, 100), (49, 51, 100),
                  (0, 50, 100), (0, 99, 100), (25.5, 74.5, 100), (100, 0, 100)]:
    angle_cases.append({"a": a, "b": b, "r": r, "expected": repr(circular_distance(a, b, r))})

norm_cases = []
for (p, r) in [(-5, 100), (105, 100), (0, 100), (99.9, 100), (-0.1, 100), (250, 100), (-250, 100)]:
    norm_cases.append({"p": p, "r": r, "expected": repr(normalize_position(p, r))})

angle_fixtures = {
    "_comment": "Generated by tools/gen_rng_fixtures.py — oracle for AngleNormalizer.ts.",
    "circularDistance": angle_cases,
    "normalizePosition": norm_cases,
}

here = os.path.dirname(os.path.abspath(__file__))
out_dir = os.path.join(here, "..", "test", "vectors")
os.makedirs(out_dir, exist_ok=True)
with open(os.path.join(out_dir, "rng.json"), "w") as f:
    json.dump(rng_fixtures, f, indent=2)
    f.write("\n")
with open(os.path.join(out_dir, "angle.json"), "w") as f:
    json.dump(angle_fixtures, f, indent=2)
    f.write("\n")

print("Wrote test/vectors/rng.json and test/vectors/angle.json")
print("  next(42)[0] =", rng_fixtures["next"]["42"][0])
print("  next(0)[0]  =", rng_fixtures["next"]["0"][0], "(remapped, nonzero)")
print("  swiftInt 77 fisherYates10 =", rng_fixtures["swiftInt"]["77:fisherYates10"]["results"])
